### PR TITLE
Please add some cash equip attributes

### PR DESCRIPTION
**Pull request by butcherCHEN**

### CODE REVIEW

**Comment by butcherCHEN** [comment]
But I don't now whether masterSpecial cash equip existing in CMS， but KMS It already exists.
Like this


The code Derived from @Kennysoft ，but he makes KMS version ，I didn't know more about CMS

**Comment by KENNYSOFT** [comment]
Oh, my code 😄

**Comment by butcherCHEN** [comment]
There seems to be one missing.  but nicktag don't seem to be cash equips
470c9fe18123264a4fb8d200c4605660910c4d1d

**Comment by Kagamia** [comment]
Thanks for your commit. 

How can I get the resource `CashItem_label_0`? Could you show me the full path from `UI.wz`?

**Comment by butcherCHEN** [comment]
@Kagamia 
The full path is here  {UI.wz/CashShop/CashItem_label}

**Comment by KENNYSOFT** [comment]
Maybe that's only in KMS.

**Comment by butcherCHEN** [comment]
@Kennysoft  Yes，I think so too。

**Pull request merged**
