### PR TITLE
Migrate all csproj files to sdk style

### PR DESCRIPTION
**Pull request by Kagamia**

### CODE REVIEW

**Comment by Kagamia** [comment]
I'm going to upgrade project files.
Please help to review and check if it breaks your build pipeline, thanks.

Note that CharasimResource is not updated yet so still we can't build it with `dotnet build` command, and .Net6/7 migration is not included in this PR.

@KENNYSOFT  @PirateIzzy

**Comment by PirateIzzy** [comment]
I migrated all of my project files to SDK style. The only issue I encountered was with these 3 EffectForm files that were part of Spadow's repo beforehand.
image
https://github.com/PirateIzzy/WzComparerR2/tree/35cdad4453b4eb077c03ade075fdb6470e89697e/WzComparerR2.Avatar/UI

They seem to be part of the kms-MixEff branch. For now I removed them since these aren't part of your repo or @KENNYSOFT 's repo.
https://github.com/jinook518/WzComparerR2/tree/kms-MixEff/WzComparerR2.Avatar/UI

**Comment by PirateIzzy** [comment]
So I have an update on this, when I try to export any GIF I receive this error.
image (2)

For some reason it isn't giving me a stack trace in error.log so I can't determine where the issue is. I tested with your CMS build and didn't receive this issue.

**Comment by Kagamia** [comment]
@PirateIzzy please check the default namespace of WzComparerR2.Commom project, and how PngEffect shader binary is embed into dll file.
In latest release I force renaming the resource name.
https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.Common/WzComparerR2.Common.csproj#L54C4-L54C156

**Comment by PirateIzzy** [comment]
I will check and see if that works. Thank you.

By the way, should line 6 be `WzComparerR2.Common`?
image

**Comment by Kagamia** [comment]
historically, all classes in `WzComparerR2.Common` are declared in `WzComparerR2` main project, for convenience I still keep the same default namespace for any new created files.

EmbedResource names are auto generated from root namespace and file path, so better to explicily declare logicalName for it.

**Comment by PirateIzzy** [comment]
Makes sense. I might take a while to get back on this since I have to integrate all the differences between KENNYSOFT and my repo vs your repo. I'm thinking some time in the future, we could unify some more features between KMS and CMS.

**Comment by PirateIzzy** [comment]
Question, is there any reason why all of these search results are highlighted? Not sure if you encountered the same.
image

**Comment by PirateIzzy** [comment]
For now I have decided to just shelve all of the changes and just focus on fixing the GIF issue. Side note, did you receive these warnings when changing the version? If so, how did you fix them?

image

**Comment by Kagamia** [comment]
> For now I have decided to just shelve all of the changes and just focus on fixing the GIF issue. Side note, did you receive these warnings when changing the version? If so, how did you fix them?
> 
> image

I see [SharpDX](https://www.nuget.org/packages/SharpDX#dependencies-body-tab) explicitly targets `.NETStandard 1.1` so I don't see the warning.
For `ICSharpCode.TextEditor` I ignore the error anyway  -> [WzComparerR2.LuaConsole.csproj](
https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.LuaConsole/WzComparerR2.LuaConsole.csproj#L39C1-L39C44)

**Comment by Kagamia** [comment]
> Question, is there any reason why all of these search results are highlighted? Not sure if you encountered the same. image
> 
> Also, seems the MapRender is giving errors when I try to update, possibly due to all the code differences between yours and KENNYSOFT's. I'm thinking I might just revert the changes and just aim to fix the GIF issue for now. image

1. Known issue, I mentioned it [here](https://github.com/Kagamia/WzComparerR2/issues/234#issuecomment-1733780440).
2. Is it caused by [this commit](https://github.com/Kagamia/WzComparerR2/commit/6faf6cf12a50b1932f87f548f8d81d1459d5753e)? I updated the state machine recently.

**Comment by PirateIzzy** [comment]
> > For now I have decided to just shelve all of the changes and just focus on fixing the GIF issue. Side note, did you receive these warnings when changing the version? If so, how did you fix them?
> > image
> 
> I see [SharpDX](https://www.nuget.org/packages/SharpDX#dependencies-body-tab) explicitly targets `.NETStandard 1.1` so I don't see the warning. For `ICSharpCode.TextEditor` I ignore the error anyway -> [WzComparerR2.LuaConsole.csproj](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.LuaConsole/WzComparerR2.LuaConsole.csproj#L39C1-L39C44)

So it seems like the warning prevents any builds from being completed in my `net6.0-windows` folder, but my `net462` folder works fine. I will see if I can figure out a solution.
image
image

**Comment by PirateIzzy** [comment]
> > Question, is there any reason why all of these search results are highlighted? Not sure if you encountered the same. image
> > Also, seems the MapRender is giving errors when I try to update, possibly due to all the code differences between yours and KENNYSOFT's. I'm thinking I might just revert the changes and just aim to fix the GIF issue for now. image
> 
> 1. Known issue, I mentioned it [here](https://github.com/Kagamia/WzComparerR2/issues/234#issuecomment-1733780440).
> 2. Is it caused by [this commit](https://github.com/Kagamia/WzComparerR2/commit/6faf6cf12a50b1932f87f548f8d81d1459d5753e)? I updated the state machine recently.

To 2, it was indeed. After reverting it, WCR2 works fine again.

**Comment by PirateIzzy** [comment]
I figured out the issue with the `net6.0-windows` build, it's working now.

**Comment by Kagamia** [comment]
@PirateIzzy Congratulations. you're following my path.
I explained the error in #224, the workaround is to inject a repaired function with [Harmony](https://github.com/pardeike/Harmony).
See https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2/Dotnet6Patches.cs

**Comment by PirateIzzy** [comment]
@Kagamia Thank you for the help. I was able to get it to work so far, will let you know if anything comes up.

**Comment by PirateIzzy** [comment]
Hi @Kagamia , so Hikari Calyx tested downloading a patch but apparently it attempted to check MapleStory.exe for checksum validation. Did you encounter this before?

image

**Comment by HikariCalyx** [comment]
> @PirateIzzy I've never seen this error before nor bug reports from community. Really curious that why the new created file is broken...
> 
> Could you double check that if the new `MapleStory.exe` is a complete executable file(MZ file)?

I can run patched MapleStory.exe successfully, it will download 384.3 minor patch version automatically from Nexon Korea server.

**Comment by Kagamia** [comment]
> > @PirateIzzy I've never seen this error before nor bug reports from community. Really curious that why the new created file is broken...
> > Could you double check that if the new `MapleStory.exe` is a complete executable file(MZ file)?
> 
> I can run patched MapleStory.exe successfully, it will download 384.3 minor patch version automatically from Nexon Korea server.

So, does it mean that crc hash algorithm returns different result between netfx and net6?

**Comment by PirateIzzy** [comment]
So it's specifically pointing to this line, not sure why. Your CMS build works with .NET 6.0.

https://github.com/PirateIzzy/WzComparerR2/blob/07495ba9b7107b438f7050d00a26f71f012f23b9/WzComparerR2/FrmPatcher.cs#L280
https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2/Patcher/WzPatcher.cs#L262

For now I tested replacing my FrmPatcher.cs with yours, and it seems to work fine. It's possible that something in the old version was causing an issue with MapleStory.exe.

**Comment by Kagamia** [comment]
To track this bug we'd better to start a new thread (issue) with the following information:

1. Can someone stable repro this error NOW? (to help confirm whether it is being fixed after investigation)
2. Is the error message (especially, the actuall hashcode) consitent?
3. Was it only occurred on specific WcR2 fork/build/edition?
4. Did someone manually verified the hashcode of new created file with [CheckSum.ComputeHash2()](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2/Patcher/Builder/CheckSum.cs) among different WcR2 version?
5. etc.

**Comment by PirateIzzy** [comment]
I can log it in my repo's Issues list. I'll include you and Hikari in it.

**Pull request merged**
