### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by PirateIzzy**

### CODE REVIEW

**Comment by PirateIzzy** [comment]
Meant to put on my repo, my mistake.

**Comment by Kagamia** [comment]
Sorry, WcR2 master branch will not merge a PR with lots of translation or language pack. It's not ready for mult-language supported, primary build for CMS & KMS simulation.

Also for GMS-ONLY contents, cause I don't have a GMS account or client. I can't test. 😢

**Comment by PirateIzzy** [comment]
That's fine, I actually meant to do a pull request on my repository, not this one; accidentally opened it for this by mistake.

**Comment by Kagamia** [comment]
I'm glad to see that you're maintaining your own WC version and making it greater :)

**Comment by PirateIzzy** [comment]
Of course! I do need to fix and translate other parts, but I'd need to figure that out.

**Pull request closed without merging**
